# include "utils.h"
program binary_tree_map_lib_test
   USE_UTILS_H
   use, intrinsic:: iso_fortran_env, only: INT8, INT16, INT32, INT64, REAL32, REAL64, REAL128
   use, non_intrinsic:: binary_tree_map_lib
   implicit none

   type(CharacterDim0Len1IntegerDim0KindINT32BinaryTreeMap):: treeMap1
   type(CharacterDim0Len2IntegerDim0KindINT32BinaryTreeMap):: treeMap2
   Integer:: n, n1, n2
   Logical:: lTmp

      call append(treeMap1, 'p', 112)
      call append(treeMap1, 'w', 119)
      call append(treeMap1, 'v', 118)
      call append(treeMap1, 'b', 98)
      call append(treeMap1, 'i', 105)
      call append(treeMap1, 'e', 101)
      call append(treeMap1, 'a', 97)
      call append(treeMap1, 'd', 100)
      call append(treeMap1, 'f', 102)
      call append(treeMap1, 'u', 117)
      call append(treeMap1, 'q', 113)
      call append(treeMap1, 'r', 114)
      call append(treeMap1, 'm', 109)
      call append(treeMap1, 'c', 99)
      call append(treeMap1, 's', 115)
      call append(treeMap1, 'g', 103)
      call append(treeMap1, 'y', 121)
      call append(treeMap1, 'o', 111)
      call append(treeMap1, 'x', 120)
      call append(treeMap1, 'j', 106)
      call append(treeMap1, 'z', 122)
      call append(treeMap1, 'k', 107)
      call append(treeMap1, 'l', 108)
      call append(treeMap1, 'h', 104)
      call append(treeMap1, 'n', 110)
      call append(treeMap1, 't', 116)
      TEST(has_key(treeMap1, 'y'))
      TEST(get_value(treeMap1, 'y', n))
      TEST(n == 121)
      TEST(has_key(treeMap1, 'd'))
      TEST(get_value(treeMap1, 'd', n))
      TEST(n == 100)
      TEST(has_key(treeMap1, 'l'))
      TEST(get_value(treeMap1, 'l', n))
      TEST(n == 108)
      TEST(has_key(treeMap1, 'j'))
      TEST(get_value(treeMap1, 'j', n))
      TEST(n == 106)
      TEST(has_key(treeMap1, 'c'))
      TEST(get_value(treeMap1, 'c', n))
      TEST(n == 99)
      TEST(has_key(treeMap1, 'z'))
      TEST(get_value(treeMap1, 'z', n))
      TEST(n == 122)
      TEST(has_key(treeMap1, 'o'))
      TEST(get_value(treeMap1, 'o', n))
      TEST(n == 111)
      TEST(has_key(treeMap1, 'r'))
      TEST(get_value(treeMap1, 'r', n))
      TEST(n == 114)
      TEST(has_key(treeMap1, 'f'))
      TEST(get_value(treeMap1, 'f', n))
      TEST(n == 102)
      TEST(has_key(treeMap1, 'w'))
      TEST(get_value(treeMap1, 'w', n))
      TEST(n == 119)
      TEST(has_key(treeMap1, 'k'))
      TEST(get_value(treeMap1, 'k', n))
      TEST(n == 107)
      TEST(has_key(treeMap1, 'q'))
      TEST(get_value(treeMap1, 'q', n))
      TEST(n == 113)
      TEST(has_key(treeMap1, 'u'))
      TEST(get_value(treeMap1, 'u', n))
      TEST(n == 117)
      TEST(has_key(treeMap1, 'h'))
      TEST(get_value(treeMap1, 'h', n))
      TEST(n == 104)
      TEST(has_key(treeMap1, 't'))
      TEST(get_value(treeMap1, 't', n))
      TEST(n == 116)
      TEST(has_key(treeMap1, 'g'))
      TEST(get_value(treeMap1, 'g', n))
      TEST(n == 103)
      TEST(has_key(treeMap1, 'i'))
      TEST(get_value(treeMap1, 'i', n))
      TEST(n == 105)
      TEST(has_key(treeMap1, 's'))
      TEST(get_value(treeMap1, 's', n))
      TEST(n == 115)
      TEST(has_key(treeMap1, 'n'))
      TEST(get_value(treeMap1, 'n', n))
      TEST(n == 110)
      TEST(has_key(treeMap1, 'e'))
      TEST(get_value(treeMap1, 'e', n))
      TEST(n == 101)
      TEST(has_key(treeMap1, 'v'))
      TEST(get_value(treeMap1, 'v', n))
      TEST(n == 118)
      TEST(has_key(treeMap1, 'p'))
      TEST(get_value(treeMap1, 'p', n))
      TEST(n == 112)
      TEST(has_key(treeMap1, 'm'))
      TEST(get_value(treeMap1, 'm', n))
      TEST(n == 109)
      TEST(has_key(treeMap1, 'b'))
      TEST(get_value(treeMap1, 'b', n))
      TEST(n == 98)
      TEST(has_key(treeMap1, 'a'))
      TEST(get_value(treeMap1, 'a', n))
      TEST(n == 97)
      TEST(has_key(treeMap1, 'x'))
      TEST(get_value(treeMap1, 'x', n))
      TEST(n == 120)

   TEST(.not.has_key(treeMap1, '/'))
   TEST(.not.get_value(treeMap1, '/', n))

   ! key is trimed
   call append(treeMap1, '| ', -1)
   TEST(has_key(treeMap1, '| '))
   TEST(get_value(treeMap1, '| ', n))
   TEST(n == -1)

   ! has_key or get_value with too long key returns .false.
   TEST(.not.has_key(treeMap1, '||'))
   TEST(.not.get_value(treeMap1, '||', n))

   ! key is not ladjusted
   call append(treeMap2, ' |', 0)
   call append(treeMap2, '|', 1)
   lTmp = get_value(treeMap2, ' |', n1)
   lTmp = get_value(treeMap2, '|', n2)
   ASSERT(n1 /= n2)

   write(OUTPUT_UNIT, *) "SUCCESS: ", __FILE__

   stop
end program binary_tree_map_lib_test
